---
abstract: 'Dump anything in a single line less than 100 characters'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.89'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Stream-Plugin-Explain-Terse
provides:
  Test::Stream::Plugin::Explain::Terse:
    file: lib/Test/Stream/Plugin/Explain/Terse.pm
    version: '0.001000'
requires:
  perl: '5.006'
  strict: '0'
  warnings: '0'
version: '0.001000'
